### ISSUE TITLE
Rebasing barfs on the terminal

### ISSUE THREAD

**Issue by arusahni** [arusahni/lolologist#24]
```
Traceback (most recent call last):
  File "/home/aru/bin/lolologist", line 9, in <module>
    load_entry_point('lolologist==0.4.0', 'console_scripts', 'lolologist')()
  File "/home/aru/.virtualenvs/lolologist-production/local/lib/python2.7/site-packages/lolologist/lolologist.py", line 375, in main
    args.func(args)
  File "/home/aru/.virtualenvs/lolologist-production/local/lib/python2.7/site-packages/lolologist/lolologist.py", line 269, in capture
    commit = self.__get_newest_commit()
  File "/home/aru/.virtualenvs/lolologist-production/local/lib/python2.7/site-packages/lolologist/lolologist.py", line 264, in __get_newest_commit
    return GitRepository(self.repo_path).get_newest_commit(translator=translator)
  File "/home/aru/.virtualenvs/lolologist-production/local/lib/python2.7/site-packages/lolologist/repository.py", line 75, in get_newest_commit
    head_ref = self.repo.head.reference.commit
  File "/home/aru/.virtualenvs/lolologist-production/local/lib/python2.7/site-packages/git/refs/symbolic.py", line 244, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '3ee54aa99532ee1d1f42fe4940b1d8975fb635f8'
[detached HEAD 3ee54aa] [Post] Switching to NeoVim (Part 1)
```

**Comment by arusahni** [comment]
Fixed.
